In [1]:
import pandas as pd
seoul_2018 = pd.read_csv("./2018.csv",encoding='cp949',parse_dates=["계약일"])

In [2]:
seoul_2018["자치구코드"].isna().sum()

np.int64(0)

In [3]:
seoul_2018["법정동코드"].isna().sum()

np.int64(0)

In [4]:
seoul_2018[["지번구분","지번구분명"]].isna().sum()

지번구분     14363
지번구분명    14363
dtype: int64

In [8]:
seoul_2018.isna().sum()

접수연도                     0
자치구코드                    0
자치구명                     0
법정동코드                    0
법정동명                     0
지번구분                 14363
지번구분명                14363
본번                   14366
부번                   14366
건물명                  14346
계약일                      0
물건금액(만원)                 0
건물면적(㎡)                  0
토지면적(㎡)              23830
층                    14346
권리구분                163980
취소일                 166717
건축년도                   245
건물용도                     0
신고구분                166717
신고한 개업공인중개사 시군구명    166717
dtype: int64

In [19]:
duple_2018 = seoul_2018.duplicated()
duple_2018

0         False
1         False
2         False
3         False
4         False
          ...
166712    False
166713    False
166714    False
166715    False
166716    False
Length: 166717, dtype: bool

In [ ]:
seoul_2018['건축년도'].value_counts()

건축년도
2003.0    8594
2004.0    7974
2002.0    7528
2018.0    6537
1988.0    5470
          ...
1944.0       2
1946.0       1
1926.0       1
1951.0       1
1912.0       1
Name: count, Length: 97, dtype: int64

In [21]:
seoul_2018['건축년도'].isna().sum()

np.int64(245)

In [22]:
seoul_2019['건축년도'].isna().sum()

NameError: name 'seoul_2019' is not defined

In [16]:
yongsan = ["후암동","용산동2가","용산동4가","갈월동","남영동","용산동1가","동자동","서계동","청파동1가","청파동2가","청파동3가","원효로1가","원효로2가","신창동","산천동","청암동","원효로3가","원효로4가","효창동","도원동","용문동","문배동","신계동","한강로1가","한강로2가","용산동3가","용산동5가","한강로3가","이촌동","이태원동","한남동","동빙고동","서빙고동","주성동","용산동6가","보광동"]
not_yongsan_2018 = seoul_2018[(seoul_2018["자치구명"]=="용산구") & (~seoul_2018["법정동명"].isin(yongsan))]

not_yongsan_2018

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
161601,2018,11170,용산구,10100,방배동,1.0,대지,890.0,19.0,방배월든빌,...,47968,48.66,24.79,3.0,NaN,NaN,2016.0,연립다세대,NaN,NaN

In [17]:
gangnam = ["역삼동","개포동","청담동","삼성동","대치동","신사동","논현동","압구정동","세곡동","자곡동","율현동","일원동","수서동","도곡동"]
not_gangnam_2018 = seoul_2018[(seoul_2018["자치구명"]=="강남구") & (~seoul_2018["법정동명"].isin(gangnam))]

not_gangnam_2018

Empty DataFrame
Columns: [접수연도, 자치구코드, 자치구명, 법정동코드, 법정동명, 지번구분, 지번구분명, 본번, 부번, 건물명, 계약일, 물건금액(만원), 건물면적(㎡), 토지면적(㎡), 층, 권리구분, 취소일, 건축년도, 건물용도, 신고구분, 신고한 개업공인중개사 시군구명]
Index: []

[0 rows x 21 columns]